#!/bin/bash
# Get operation from terminal.
ops=$1

# Call relevant function.
if test $ops = dims
then
  echo dims
elif test $ops = transpose
then
  echo transpose
elif test $ops = mean
then
  echo mean
elif test $ops = add
then
  echo add
else
  echo multiply
fi
