#!/bin/bash

# This is a testing script for assignment 3. First argument is the number of tests to run.

# Get number of tests to run.
tests=$1

# Iterator
testNum=0

# Test the output of the python script. Record the outcome in array.
while test $testNum -lt $tests
do
  python3 mypython.py
  testNum=$((testNum + 1))
done
